checks:
    php:
        custom_coding_standard:
            git_repository: 'https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards'
            ruleset_path: 'WordPress-Core/ruleset.xml'
tools:
    php_code_sniffer:
        config:
            standard: "WordPress"